# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  dutchnews.ru:
    site_hosts:
      - canonical: dutchnews.dev
    local_path: ../dutchnews.ru # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: hollandlive@gmail.com
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
